<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manejo de errores con callbacks </title>
</head>
<body>
    <script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous">
    </script>

  <script>
      const API_URL = 'https://swapi.dev/api/'
      const PEOPLE_URL = 'people/:id'


      const opts = {crossDomanin: true}

    //   $.get(lukeUrl, opts, onResponse)

      function obtenerPersonaje(id, callback){
        const url = `${API_URL}${PEOPLE_URL.replace(':id',id)}`

        $.get(url, opts, callback).fail(function(){
            console.log(`Sucedio un error no se pudo conseguir el personaje ${id}`)
        })
              
      }


      obtenerPersonaje(1, function(personaje){
        console.log(`Hola, yo soy ${personaje.name}`)  

        obtenerPersonaje(2, function(personaje){
            console.log(`Hola, yo soy ${personaje.name}`)  

            obtenerPersonaje(2, function(personaje){
                        console.log(`Hola, yo soy ${personaje.name}`) 

                obtenerPersonaje(3, function(personaje){
                            console.log(`Hola, yo soy ${personaje.name}`)  

                    obtenerPersonaje(4, function(personaje){
                                console.log(`Hola, yo soy ${personaje.name}`) 

                        obtenerPersonaje(5, function(personaje){
                                    console.log(`Hola, yo soy ${personaje.name}`) 

                            obtenerPersonaje(6, function(personaje){
                                        console.log(`Hola, yo soy ${personaje.name}`)  

                                obtenerPersonaje(7, function(personaje){
                                    console.log(`Hola, yo soy ${personaje.name}`)
                                })
                            })
                        })
                    })
                })
            })

        })
      })
      


 






  </script>

<h1>Manejo de errores con callbacks</h1>

<p>
    Para solucionar el problema de quedarnos sin conexión, u otro error similar, en medio de una sucesión de <br>
    callbacks utilizamos el método fail().



</p>
    
</body>
</html>